### ISSUE TITLE
GRC Flows

### ISSUE THREAD

**Issue by alexbirkett** [kevinmehall/rtlsdr-433m-sensor#3]
Hi,

Was any of the python generated with GNU Radio Companion? If so, do you have the flows, i'd be very interested to see them.

Thanks for your help

Alex

**Comment by kevinmehall** [comment]
It was loosely based on previous experiments in AM demodulation in GRC, but was rewritten in cleaner python. See `rtlsdr_am_stream.__init__` for the GNU Radio flow part. Basically:
 OsmoSDR source -> freq_xlating_fir_filter -> am_demod -> rational_resampler -> custom queue sink.
